-- ========================================
-- AJOUT TABLE PUSH_NOTIFICATION_LOGS
-- Requise par l'edge function pour l'idempotence
-- ========================================

-- Table pour les logs de notifications push
CREATE TABLE IF NOT EXISTS push_notification_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notif_id TEXT NOT NULL UNIQUE,
  user_id TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'default',
  title TEXT,
  body TEXT,
  url TEXT,
  icon_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending', -- pending, sent, failed
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  sent_at TIMESTAMP WITH TIME ZONE
);

-- Index pour performances
CREATE INDEX IF NOT EXISTS idx_push_notification_logs_notif_id ON push_notification_logs(notif_id);
CREATE INDEX IF NOT EXISTS idx_push_notification_logs_user_id ON push_notification_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_push_notification_logs_status ON push_notification_logs(status);

-- Activer RLS
ALTER TABLE push_notification_logs ENABLE ROW LEVEL SECURITY;

-- Politiques RLS
DROP POLICY IF EXISTS "push_notification_logs_insert_all" ON push_notification_logs;
CREATE POLICY "push_notification_logs_insert_all" ON push_notification_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "push_notification_logs_read_all" ON push_notification_logs;
CREATE POLICY "push_notification_logs_read_all" ON push_notification_logs FOR SELECT USING (true);

DROP POLICY IF EXISTS "push_notification_logs_update_all" ON push_notification_logs;
CREATE POLICY "push_notification_logs_update_all" ON push_notification_logs FOR UPDATE USING (true);

DO $$
BEGIN
  RAISE NOTICE 'Table push_notification_logs créée avec succès';
END $$;
