-- Créer la table live_room_likes pour les likes sur les salons live
-- V600000 - Système de likes sur les live rooms

-- 1. Créer la table live_room_likes
CREATE TABLE IF NOT EXISTS live_room_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES live_rooms(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Contrainte d'unicité : un utilisateur ne peut liker une salle qu'une seule fois
    UNIQUE(room_id, user_id)
);

-- 2. Activer RLS
ALTER TABLE live_room_likes ENABLE ROW LEVEL SECURITY;

-- 3. Politiques RLS
-- Politique de lecture : les utilisateurs peuvent voir les likes de toutes les salles
CREATE POLICY "live_room_likes_read_all" ON live_room_likes
    FOR SELECT USING (true);

-- Politique d'insertion : les utilisateurs authentifiés peuvent liker des salles
CREATE POLICY "live_room_likes_insert_own" ON live_room_likes
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Politique de suppression : les utilisateurs peuvent supprimer leurs propres likes
CREATE POLICY "live_room_likes_delete_own" ON live_room_likes
    FOR DELETE USING (auth.uid() = user_id);

-- 4. Index pour optimiser les performances
CREATE INDEX IF NOT EXISTS idx_live_room_likes_room_id ON live_room_likes(room_id);
CREATE INDEX IF NOT EXISTS idx_live_room_likes_user_id ON live_room_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_live_room_likes_created_at ON live_room_likes(created_at);

-- 5. Trigger pour mettre à jour le compteur de likes dans live_rooms (optionnel)
CREATE OR REPLACE FUNCTION update_live_room_likes_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE live_rooms 
        SET likes_count = likes_count + 1 
        WHERE id = NEW.room_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE live_rooms 
        SET likes_count = GREATEST(likes_count - 1, 0) 
        WHERE id = OLD.room_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 6. Créer le trigger
DROP TRIGGER IF EXISTS trigger_update_live_room_likes_count ON live_room_likes;
CREATE TRIGGER trigger_update_live_room_likes_count
    AFTER INSERT OR DELETE ON live_room_likes
    FOR EACH ROW EXECUTE FUNCTION update_live_room_likes_count();

-- 7. Ajouter la colonne likes_count à live_rooms si elle n'existe pas
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name='live_rooms' AND column_name='likes_count'
    ) THEN
        ALTER TABLE live_rooms ADD COLUMN likes_count INTEGER DEFAULT 0;
    END IF;
END
$$;
