-- Créer la table live_room_likes pour les likes sur les salons live
-- V600000 - Système de likes sur les live rooms (VERSION FINALE CORRIGÉE)

-- 1. D'abord, créer ou mettre à jour la table live_rooms avec les bons types
-- NOTE: host_id doit être UUID pour référencer auth.users(id) correctement
DO $$
BEGIN
    -- Supprimer la table live_rooms si elle existe avec des types incorrects
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'live_rooms' AND table_schema = 'public') THEN
        DROP TABLE IF EXISTS live_rooms CASCADE;
        RAISE NOTICE 'Ancienne table live_rooms supprimée pour recréation avec les bons types';
    END IF;
    
    -- Créer la table live_rooms avec les types corrects
    CREATE TABLE live_rooms (
        id TEXT PRIMARY KEY DEFAULT (gen_random_uuid()::text),
        title TEXT NOT NULL,
        description TEXT,
        host_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
        genre TEXT DEFAULT 'music',
        is_live BOOLEAN DEFAULT false,
        is_private BOOLEAN DEFAULT false,
        max_participants INTEGER DEFAULT 100,
        current_participants INTEGER DEFAULT 0,
        likes_count INTEGER DEFAULT 0,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    
    RAISE NOTICE 'Table live_rooms créée avec les types corrects';
END $$;

-- 2. Activer RLS sur live_rooms
ALTER TABLE live_rooms ENABLE ROW LEVEL SECURITY;

-- 3. Politiques RLS pour live_rooms
DROP POLICY IF EXISTS "live_rooms_read_all" ON live_rooms;
CREATE POLICY "live_rooms_read_all" ON live_rooms
    FOR SELECT USING (true);
    
DROP POLICY IF EXISTS "live_rooms_insert_own" ON live_rooms;
CREATE POLICY "live_rooms_insert_own" ON live_rooms
    FOR INSERT WITH CHECK (auth.uid() = host_id);
    
DROP POLICY IF EXISTS "live_rooms_update_own" ON live_rooms;
CREATE POLICY "live_rooms_update_own" ON live_rooms
    FOR UPDATE USING (auth.uid() = host_id);
    
DROP POLICY IF EXISTS "live_rooms_delete_own" ON live_rooms;
CREATE POLICY "live_rooms_delete_own" ON live_rooms
    FOR DELETE USING (auth.uid() = host_id);

-- 4. Créer la table live_room_likes avec les types corrects
-- room_id est TEXT (pour correspondre à live_rooms.id)
-- user_id est UUID (pour correspondre à auth.users.id)
CREATE TABLE IF NOT EXISTS live_room_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id TEXT NOT NULL REFERENCES live_rooms(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(room_id, user_id)
);

-- 5. Activer RLS sur live_room_likes
ALTER TABLE live_room_likes ENABLE ROW LEVEL SECURITY;

-- 6. Politiques RLS pour live_room_likes
DROP POLICY IF EXISTS "live_room_likes_read_all" ON live_room_likes;
CREATE POLICY "live_room_likes_read_all" ON live_room_likes
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "live_room_likes_insert_own" ON live_room_likes;
CREATE POLICY "live_room_likes_insert_own" ON live_room_likes
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "live_room_likes_delete_own" ON live_room_likes;
CREATE POLICY "live_room_likes_delete_own" ON live_room_likes
    FOR DELETE USING (auth.uid() = user_id);

-- 7. Index pour optimiser les performances
CREATE INDEX IF NOT EXISTS idx_live_room_likes_room_id ON live_room_likes(room_id);
CREATE INDEX IF NOT EXISTS idx_live_room_likes_user_id ON live_room_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_live_room_likes_created_at ON live_room_likes(created_at);

-- 8. Trigger pour mettre à jour le compteur de likes dans live_rooms
CREATE OR REPLACE FUNCTION update_live_room_likes_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE live_rooms 
        SET likes_count = likes_count + 1 
        WHERE id = NEW.room_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE live_rooms 
        SET likes_count = GREATEST(likes_count - 1, 0) 
        WHERE id = OLD.room_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 9. Créer le trigger
DROP TRIGGER IF EXISTS trigger_update_live_room_likes_count ON live_room_likes;
CREATE TRIGGER trigger_update_live_room_likes_count
    AFTER INSERT OR DELETE ON live_room_likes
    FOR EACH ROW EXECUTE FUNCTION update_live_room_likes_count();

-- 10. Validation finale
DO $$
DECLARE
    room_id_type TEXT;
    room_id_maxlen INTEGER;
    host_id_type TEXT;
    likes_room_id_type TEXT;
    likes_user_id_type TEXT;
BEGIN
    RAISE NOTICE '=== VALIDATION FINALE ===';
    
    -- Vérifier que les tables existent
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'live_rooms' AND table_schema = 'public') THEN
        RAISE NOTICE '✓ Table live_rooms existe';
        
        -- Vérifier les types des colonnes
        SELECT data_type, character_maximum_length
        INTO room_id_type, room_id_maxlen
        FROM information_schema.columns 
        WHERE table_name = 'live_rooms' 
        AND column_name = 'id' 
        AND table_schema = 'public';
        
        SELECT data_type INTO host_id_type
        FROM information_schema.columns 
        WHERE table_name = 'live_rooms' 
        AND column_name = 'host_id' 
        AND table_schema = 'public';
        
        RAISE NOTICE '  - live_rooms.id: %', room_id_type;
        RAISE NOTICE '  - live_rooms.host_id: %', host_id_type;
    ELSE
        RAISE EXCEPTION '✗ Table live_rooms manquante';
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'live_room_likes' AND table_schema = 'public') THEN
        RAISE NOTICE '✓ Table live_room_likes existe';
        
        -- Vérifier les types des colonnes
        SELECT data_type INTO likes_room_id_type
        FROM information_schema.columns 
        WHERE table_name = 'live_room_likes' 
        AND column_name = 'room_id' 
        AND table_schema = 'public';
        
        SELECT data_type INTO likes_user_id_type
        FROM information_schema.columns 
        WHERE table_name = 'live_room_likes' 
        AND column_name = 'user_id' 
        AND table_schema = 'public';
        
        RAISE NOTICE '  - live_room_likes.room_id: %', likes_room_id_type;
        RAISE NOTICE '  - live_room_likes.user_id: %', likes_user_id_type;
    ELSE
        RAISE EXCEPTION '✗ Table live_room_likes manquante';
    END IF;
    
    -- Vérifier les contraintes étrangères
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
        WHERE tc.table_name = 'live_room_likes' 
        AND tc.constraint_type = 'FOREIGN KEY'
        AND tc.table_schema = 'public'
    ) THEN
        RAISE NOTICE '✓ Contraintes étrangères présentes sur live_room_likes';
    ELSE
        RAISE NOTICE '⚠ Aucune contrainte étrangère détectée sur live_room_likes';
    END IF;
    
    -- Vérifier RLS
    IF EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'live_room_likes' 
        AND schemaname = 'public'
    ) THEN
        RAISE NOTICE '✓ Politiques RLS présentes sur live_room_likes';
    ELSE
        RAISE NOTICE '⚠ Aucune politique RLS détectée sur live_room_likes';
    END IF;
    
    RAISE NOTICE '=== INSTALLATION TERMINÉE AVEC SUCCÈS ===';
    RAISE NOTICE 'Types utilisés:';
    RAISE NOTICE '- live_rooms.id: TEXT';
    RAISE NOTICE '- live_rooms.host_id: UUID';
    RAISE NOTICE '- live_room_likes.room_id: TEXT';
    RAISE NOTICE '- live_room_likes.user_id: UUID';
    RAISE NOTICE '';
    RAISE NOTICE 'Compatibilité:';
    RAISE NOTICE '- auth.users.id: UUID ✓';
    RAISE NOTICE '- live_rooms.host_id → auth.users.id: UUID → UUID ✓';
    RAISE NOTICE '- live_room_likes.user_id → auth.users.id: UUID → UUID ✓';
    RAISE NOTICE '- live_room_likes.room_id → live_rooms.id: TEXT → TEXT ✓';
END $$;

-- 11. Insérer des données de test si la table est vide
DO $$
BEGIN
    IF (SELECT COUNT(*) FROM live_rooms) = 0 THEN
        -- Essayer d'insérer avec un utilisateur existant
        BEGIN
            INSERT INTO live_rooms (title, description, host_id, genre, is_live)
            VALUES 
                ('Test Room 1', 'Salle de test pour les likes', auth.uid(), 'music', true),
                ('Test Room 2', 'Autre salle de test', auth.uid(), 'pop', true);
            
            RAISE NOTICE 'Données de test insérées dans live_rooms';
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Impossible d''insérer les données de test: %', SQLERRM;
            RAISE NOTICE 'Vous devrez insérer manuellement des données avec un utilisateur authentifié';
        END;
    END IF;
END $$;
