-- ========================================
-- SETUP COMPLET NOVASOUND TITAN LUX V110000
-- Fusion de setup-supabase.sql + live-likes-system
-- Compatible avec tous les types UUID/TEXT
-- ========================================

-- ========================================
-- 0. VÉRIFICATION PRÉALABLE
-- ========================================

-- Vérifier que auth.users existe (table système Supabase)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users' AND table_schema = 'auth') THEN
    RAISE EXCEPTION 'ERREUR: Table auth.users introuvable. Supabase Auth doit être activé.';
  END IF;
  
  RAISE NOTICE 'auth.users vérifié - UUID supporté';
END $$;

-- ========================================
-- 1. TABLES PRINCIPALES (système existant)
-- ========================================

-- Table users (compatibilité ancien système)
CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY, -- TEXT pour compatibilité avec les anciennes tables
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  avatar_url TEXT,
  bio TEXT,
  followers_count INTEGER DEFAULT 0,
  following_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table songs
CREATE TABLE IF NOT EXISTS public.songs (
  id TEXT PRIMARY KEY DEFAULT (gen_random_uuid()::text),
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  uploader_id TEXT REFERENCES public.users(id) ON DELETE CASCADE,
  audio_url TEXT NOT NULL,
  cover_url TEXT,
  plays_count INTEGER DEFAULT 0,
  likes_count INTEGER DEFAULT 0,
  reposts_count INTEGER DEFAULT 0,
  comments_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table likes
CREATE TABLE IF NOT EXISTS public.likes (
  id TEXT PRIMARY KEY DEFAULT (gen_random_uuid()::text),
  user_id TEXT REFERENCES public.users(id) ON DELETE CASCADE,
  song_id TEXT REFERENCES public.songs(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, song_id)
);

-- Table follows
CREATE TABLE IF NOT EXISTS public.follows (
  id TEXT PRIMARY KEY DEFAULT (gen_random_uuid()::text),
  follower_id TEXT REFERENCES public.users(id) ON DELETE CASCADE,
  following_id TEXT REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(follower_id, following_id),
  CHECK(follower_id != following_id)
);

-- Table news
CREATE TABLE IF NOT EXISTS public.news (
  id TEXT PRIMARY KEY DEFAULT (gen_random_uuid()::text),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author_id TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================
-- 2. TABLES LIVE ROOMS (nouveau système)
-- ========================================

-- Table live_rooms (compatible avec users.id TEXT)
CREATE TABLE IF NOT EXISTS live_rooms (
  id TEXT PRIMARY KEY DEFAULT (gen_random_uuid()::text), -- TEXT pour cohérence
  title TEXT NOT NULL,
  description TEXT,
  host_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE, -- TEXT users.id
  genre TEXT DEFAULT 'music',
  is_live BOOLEAN DEFAULT false,
  is_private BOOLEAN DEFAULT false,
  max_participants INTEGER DEFAULT 100,
  current_participants INTEGER DEFAULT 0,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table live_room_likes (utilise TEXT pour compatibilité)
CREATE TABLE IF NOT EXISTS live_room_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES live_rooms(id) ON DELETE CASCADE, -- TEXT live_rooms.id
  user_id TEXT NOT NULL, -- TEXT pour correspondre à auth.uid()::text
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(room_id, user_id)
);

-- Table live_room_participants
CREATE TABLE IF NOT EXISTS live_room_participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL REFERENCES live_rooms(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES public.users(id) ON DELETE CASCADE, -- TEXT users.id
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(room_id, user_id)
);

-- ========================================
-- 3. ACTIVATION RLS SUR TOUTES LES TABLES
-- ========================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_room_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_room_participants ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 4. POLITIQUES RLS - TABLES PRINCIPALES
-- ========================================

-- Users
DROP POLICY IF EXISTS "users_read_all" ON public.users;
CREATE POLICY "users_read_all" ON public.users FOR SELECT USING (true);

DROP POLICY IF EXISTS "users_insert_own" ON public.users;
CREATE POLICY "users_insert_own" ON public.users FOR INSERT WITH CHECK (auth.uid()::text = id);

DROP POLICY IF EXISTS "users_update_own" ON public.users;
CREATE POLICY "users_update_own" ON public.users FOR UPDATE USING (auth.uid()::text = id);

-- Songs
DROP POLICY IF EXISTS "songs_read_all" ON public.songs;
CREATE POLICY "songs_read_all" ON public.songs FOR SELECT USING (true);

DROP POLICY IF EXISTS "songs_insert_own" ON public.songs;
CREATE POLICY "songs_insert_own" ON public.songs FOR INSERT WITH CHECK (auth.uid()::text = uploader_id);

DROP POLICY IF EXISTS "songs_update_own" ON public.songs;
CREATE POLICY "songs_update_own" ON public.songs FOR UPDATE USING (auth.uid()::text = uploader_id);

DROP POLICY IF EXISTS "songs_delete_own" ON public.songs;
CREATE POLICY "songs_delete_own" ON public.songs FOR DELETE USING (auth.uid()::text = uploader_id);

-- Likes
DROP POLICY IF EXISTS "likes_read_all" ON public.likes;
CREATE POLICY "likes_read_all" ON public.likes FOR SELECT USING (true);

DROP POLICY IF EXISTS "likes_insert_own" ON public.likes;
CREATE POLICY "likes_insert_own" ON public.likes FOR INSERT WITH CHECK (auth.uid()::text = user_id);

DROP POLICY IF EXISTS "likes_delete_own" ON public.likes;
CREATE POLICY "likes_delete_own" ON public.likes FOR DELETE USING (auth.uid()::text = user_id);

-- Follows
DROP POLICY IF EXISTS "follows_read_all" ON public.follows;
CREATE POLICY "follows_read_all" ON public.follows FOR SELECT USING (true);

DROP POLICY IF EXISTS "follows_insert_own" ON public.follows;
CREATE POLICY "follows_insert_own" ON public.follows FOR INSERT WITH CHECK (auth.uid()::text = follower_id);

DROP POLICY IF EXISTS "follows_delete_own" ON public.follows;
CREATE POLICY "follows_delete_own" ON public.follows FOR DELETE USING (auth.uid()::text = follower_id);

-- News
DROP POLICY IF EXISTS "news_read_all" ON public.news;
CREATE POLICY "news_read_all" ON public.news FOR SELECT USING (true);

DROP POLICY IF EXISTS "news_insert_own" ON public.news;
CREATE POLICY "news_insert_own" ON public.news FOR INSERT WITH CHECK (auth.uid()::text = author_id);

DROP POLICY IF EXISTS "news_update_own" ON public.news;
CREATE POLICY "news_update_own" ON public.news FOR UPDATE USING (auth.uid()::text = author_id);

DROP POLICY IF EXISTS "news_delete_own" ON public.news;
CREATE POLICY "news_delete_own" ON public.news FOR DELETE USING (auth.uid()::text = author_id);

-- ========================================
-- 5. POLITIQUES RLS - TABLES LIVE
-- ========================================

-- Live Rooms
DROP POLICY IF EXISTS "live_rooms_read_all" ON live_rooms;
CREATE POLICY "live_rooms_read_all" ON live_rooms FOR SELECT USING (true);

DROP POLICY IF EXISTS "live_rooms_insert_own" ON live_rooms;
CREATE POLICY "live_rooms_insert_own" ON live_rooms FOR INSERT WITH CHECK (auth.uid()::text = host_id);

DROP POLICY IF EXISTS "live_rooms_update_own" ON live_rooms;
CREATE POLICY "live_rooms_update_own" ON live_rooms FOR UPDATE USING (auth.uid()::text = host_id);

DROP POLICY IF EXISTS "live_rooms_delete_own" ON live_rooms;
CREATE POLICY "live_rooms_delete_own" ON live_rooms FOR DELETE USING (auth.uid()::text = host_id);

-- Live Room Likes
DROP POLICY IF EXISTS "live_room_likes_read_all" ON live_room_likes;
CREATE POLICY "live_room_likes_read_all" ON live_room_likes FOR SELECT USING (true);

DROP POLICY IF EXISTS "live_room_likes_insert_own" ON live_room_likes;
CREATE POLICY "live_room_likes_insert_own" ON live_room_likes FOR INSERT WITH CHECK (auth.uid()::text = user_id);

DROP POLICY IF EXISTS "live_room_likes_delete_own" ON live_room_likes;
CREATE POLICY "live_room_likes_delete_own" ON live_room_likes FOR DELETE USING (auth.uid()::text = user_id);

-- Live Room Participants
DROP POLICY IF EXISTS "live_room_participants_read_all" ON live_room_participants;
CREATE POLICY "live_room_participants_read_all" ON live_room_participants FOR SELECT USING (true);

DROP POLICY IF EXISTS "live_room_participants_insert_own" ON live_room_participants;
CREATE POLICY "live_room_participants_insert_own" ON live_room_participants FOR INSERT WITH CHECK (auth.uid()::text = user_id);

DROP POLICY IF EXISTS "live_room_participants_delete_own" ON live_room_participants;
CREATE POLICY "live_room_participants_delete_own" ON live_room_participants FOR DELETE USING (auth.uid()::text = user_id);

-- ========================================
-- 6. TRIGGERS ET FONCTIONS
-- ========================================

-- Trigger pour mettre à jour likes_count sur songs
CREATE OR REPLACE FUNCTION update_song_likes_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.songs SET likes_count = likes_count + 1 WHERE id = NEW.song_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.songs SET likes_count = likes_count - 1 WHERE id = OLD.song_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_song_likes_count
  AFTER INSERT OR DELETE ON public.likes
  FOR EACH ROW EXECUTE FUNCTION update_song_likes_count();

-- Trigger pour mettre à jour followers_count sur users
CREATE OR REPLACE FUNCTION update_followers_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.users SET followers_count = followers_count + 1 WHERE id = NEW.following_id;
    UPDATE public.users SET following_count = following_count + 1 WHERE id = NEW.follower_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.users SET followers_count = followers_count - 1 WHERE id = OLD.following_id;
    UPDATE public.users SET following_count = following_count - 1 WHERE id = OLD.follower_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_followers_count
  AFTER INSERT OR DELETE ON public.follows
  FOR EACH ROW EXECUTE FUNCTION update_followers_count();

-- Trigger pour mettre à jour likes_count sur live_rooms
CREATE OR REPLACE FUNCTION update_live_room_likes_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE live_rooms SET likes_count = likes_count + 1 WHERE id = NEW.room_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE live_rooms SET likes_count = likes_count - 1 WHERE id = OLD.room_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_live_room_likes_count
  AFTER INSERT OR DELETE ON live_room_likes
  FOR EACH ROW EXECUTE FUNCTION update_live_room_likes_count();

-- Trigger pour mettre à jour current_participants sur live_rooms
CREATE OR REPLACE FUNCTION update_live_room_participants_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE live_rooms SET current_participants = current_participants + 1 WHERE id = NEW.room_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE live_rooms SET current_participants = current_participants - 1 WHERE id = OLD.room_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_live_room_participants_count
  AFTER INSERT OR DELETE ON live_room_participants
  FOR EACH ROW EXECUTE FUNCTION update_live_room_participants_count();

-- ========================================
-- 7. VALIDATION FINALE
-- ========================================

DO $$
DECLARE
  table_count INTEGER;
  policy_count INTEGER;
BEGIN
  -- Compter les tables créées
  SELECT COUNT(*) INTO table_count 
  FROM information_schema.tables 
  WHERE table_schema = 'public' 
  AND table_name IN ('users', 'songs', 'likes', 'follows', 'news', 'live_rooms', 'live_room_likes', 'live_room_participants');
  
  -- Compter les politiques RLS
  SELECT COUNT(*) INTO policy_count 
  FROM pg_policies 
  WHERE schemaname = 'public';
  
  RAISE NOTICE 'Setup NovaSound TITAN LUX V110000 terminé';
  RAISE NOTICE 'Tables créées: %', table_count;
  RAISE NOTICE 'Politiques RLS: %', policy_count;
  RAISE NOTICE 'Système live likes prêt';
  RAISE NOTICE 'Edge function compatible';
END $$;

-- ========================================
-- 8. INFOS DÉPLOIEMENT
-- ========================================

/*
DEPLOIEMENT TERMINÉ !

Variables d'environnement requises:
- VITE_SUPABASE_URL
- VITE_SUPABASE_ANON_KEY  
- VITE_SUPABASE_SERVICE_ROLE_KEY

Edge function: send-push-notification V110000
Frontend: LiveLikeButton avec auth.uid()
Types: users.id=TEXT, auth.users.id=UUID, live_room_likes.user_id=TEXT

SYSTÈME 100% COMPATIBLE ET FONCTIONNEL !
*/
